runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  CLOUD_STORAGE_BUCKET: cloud-computing-project-350613
  WEATHER_API_KEY: cbe47bc6ab381e24dcfc8be0c63861e2
  SENDGRID_KEY: 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